### PR TITLE
re-add bytesRead

### PR DESCRIPTION
**Pull request by szymonkaliski**
Per this comment https://github.com/adafruit/Adafruit_APDS9960/commit/bc9b9c2f177959e722efb4a2e54c6b54dda2ac9b#commitcomment-32102305

### CODE REVIEW

**Comment by ladyada** [comment]
thanx - did you run the hardware test after the PR? if not, lets add that to the workflow!

**Comment by szymonkaliski** [comment]
Hmm, I believe I didn't have the hardware when I was working on this lib at the beginning, and that introduced the bug, that this PR is (hopefully) solving — this PR is s a "hotfix", didn't test though yet.

**Comment by ladyada** [comment]
fixed travis - this still needs a hardware test - @hoffmannjan will do it after the next library :)

**Comment by ladyada** [comment]
@szymonkaliski @hoffmannjan please bump this to a bugfix release so it goes out!

**Comment by hoffmannjan** [comment]
this is done

**Pull request merged**
